# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pollock}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gavin Montague"]
  s.date = %q{2010-03-25}
  s.default_executable = %q{pollockserver}
  s.description = %q{A little Sinatra and RMagick to generate placeholder images via an http call.  Heavily inspired by http://placehold.it}
  s.email = %q{gavin@leftbrained.co.uk}
  s.executables = ["pollockserver"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/pollockserver",
     "lib/pollock/image.rb",
     "lib/pollock/webapp.rb",
     "public/images/faux-pollock-alt.jpg",
     "public/images/faux-pollock.jpg",
     "public/index.html",
     "public/placeholders/100x100.jpg",
     "public/placeholders/100x200.jpg",
     "public/placeholders/200x100-label.jpg",
     "public/placeholders/200x100.jpg",
     "public/placeholders/305x100-ff____.jpg",
     "public/placeholders/305x100-x-FF0000.jpg",
     "public/placeholders/305x100.jpg",
     "public/placeholders/5000x200-______.jpg",
     "public/placeholders/5000x200-foo-999000.jpg",
     "public/placeholders/5000x200.jpg",
     "public/placeholders/500x200.jpg",
     "public/stylesheets/screen.css",
     "test/helper.rb",
     "test/test_image.rb",
     "test/tmp/200x200-wow__i_m_a_label.jpg",
     "test/tmp/200x200.jpg",
     "test/tmp/200x200.png",
     "test/tmp/200x300.jpg"
  ]
  s.homepage = %q{http://github.com/govan/pollock}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A gem to save you reaching for Photoshop during html wireframing.}
  s.test_files = [
    "test/helper.rb",
     "test/test_image.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<rmagick>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<rmagick>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
  end
end

